version: 1.1.3.{build}

platform:
  - x86
  - x64

environment:
  PATH:  C:\Program Files\PowerShell\7;%PATH%,C:\Program Files\Git\cmd;%PATH%
  CL_OPTIONS: /W3 /D_CRT_SECURE_NO_DEPRECATE /DWIN32_LEAN_AND_MEAN /GS /MT /DHAVE_CONFIG_H /I%APPVEYOR_BUILD_FOLDER%
  GENGETOPT: /usr/bin/gengetopt.exe --include-getopt
  HELP2MAN: /usr/bin/true # don't generate manual files
  # If AppVeyor comes with OpenSSL 1.1.0 installed
  #OPENSSL_1_1_0_FLAGS: /DHAVE_ASN1_STRING_GET0_DATA=1 /DHAVE_DECL_OPENSSL_ZALLOC=1 /DHAVE_DH_GET0_KEY=1 /DHAVE_DH_GET0_PQG=1 /DHAVE_DH_SET0_KEY=1 /DHAVE_DH_SET0_PQG=1 /DHAVE_ECDSA_SIG_GET0=1 /DHAVE_ECDSA_SIG_SET0=1 /DHAVE_EC_KEY_METHOD=1 /DHAVE_RSA_GET0_KEY=1 /DHAVE_RSA_SET0_KEY=1

  matrix:
    - VSVER: 14


install:
  - echo "Setting up environment..."
  - choco install powershell-core git -y
  - pwsh -Command "Write-Host 'PowerShell Core is available!'"
  - if [%Platform%]==[x86] (
      set PLATFORM_ARCH=x86
      set OPENSSL_PLATFORM=Win32
    ) else (
      set PLATFORM_ARCH=x64
      set OPENSSL_PLATFORM=Win64
    )
  - set PATH=C:\Python%PYTHON_VERSION%;%PATH%
  - python -m ensurepip --upgrade
  - pip install -U wheel setuptools
  - echo "Python environment set up."


  - bash -c "pacman -Syu --noconfirm"
  - bash -c "pacman --needed --noconfirm -S autoconf automake libtool gengetopt swig"

build_script:
  - echo "Starting build process..."
  - bash -c "autoreconf -i"
  - bash -c "./configure --prefix=/"
  - make -C src cvc-print-cmdline.c cvc-create-cmdline.c
  - cd src
  - cl /I%OPENSSL_DIR%\include /I. /DX509DIR=\"/\" /DCVCDIR=\"/\" %CL_OPTIONS% /c *.c
  - lib /out:libeacMT.lib *.obj
  - cl /I%OPENSSL_DIR%\include /I. libeacMT.lib %OPENSSL_DIR%\lib\VC\static\libcryptoMT.lib *.c
  - cd ..


  - echo "Building Python bindings..."
  - cd bindings/python
  - swig -python -outdir . -I.. eac.i
  - cl /I%OPENSSL_DIR%\include /I%PYTHON_INCLUDE% /I..\..\src %CL_OPTIONS% /c eac_wrap.c
  - link /out:_eac.pyd /dll eac_wrap.obj %PYTHON_LIB% ..\..\src\libeacMT.lib
  - cd ../..

  - echo "Packaging artifacts..."
  - mkdir -p %DESTDIR%/bin
  - cp src/eactest.exe %DESTDIR%/bin
  - cp src/cvc-create.exe %DESTDIR%/bin
  - cp src/cvc-print.exe %DESTDIR%/bin
  - cp bindings/python/*.py %DESTDIR%/bin
  - bash -c "$OPENSSL_DIR/bin/openssl.exe version >> %DESTDIR%/dependencies.txt"

  - echo "Running tests..."
  - $DESTDIR/bin/eactest.exe
  - python bindings/python/test.py


  - 7z a %ARTIFACT%.zip %DESTDIR% > nul
  - appveyor PushArtifact %ARTIFACT%.zip

cache:
  - C:\msys64\var\cache\pacman\pkg\gengetopt* -> appveyor.yml
  - C:\msys64\var\cache\pacman\pkg\swig* -> appveyor.yml
